import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const source=readFileSync(new URL('../public/sw.js',import.meta.url),'utf8');
function worker(){const handlers={},stored=new Map();let calls=0;const context={URL,Response,Promise,console,fetch:async()=>{calls++;throw new Error('Offline');},caches:{async open(){return {async match(key){return stored.get(typeof key==='string'?key:key.url);},async put(k,v){stored.set(k,v);},async addAll(){}};},async keys(){return[];},async delete(){}},self:{location:{origin:'https://demo.test'},clients:{async claim(){}},skipWaiting:async()=>{},addEventListener:(name,fn)=>handlers[name]=fn}};vm.runInNewContext(source,context);return {context,handlers,stored,get calls(){return calls;}};}
test('offline navigation returns cached app shell',async()=>{const w=worker();w.stored.set('/',new Response('Field Screening shell'));let result;w.handlers.fetch({request:{url:'https://demo.test/',method:'GET',mode:'navigate',headers:new Headers()},respondWith(p){result=p;}});assert.equal(await (await result).text(),'Field Screening shell');});
test('first ever offline navigation returns network error when no shell exists',async()=>{const w=worker();let result;w.handlers.fetch({request:{url:'https://demo.test/',method:'GET',mode:'navigate',headers:new Headers()},respondWith(p){result=p;}});assert.equal((await result).type,'error');});
test('API and auth are never handled by service worker cache',()=>{const w=worker();for(const path of ['/api/submissions','/signin-with-chatgpt'])w.handlers.fetch({request:{url:'https://demo.test'+path,method:'GET',mode:'navigate',headers:new Headers()},respondWith(){assert.fail('must not cache');}});assert.equal(w.calls,0);});
test('mutations pass directly to network',()=>{const w=worker();w.handlers.fetch({request:{url:'https://demo.test/api/submissions',method:'POST',headers:new Headers()},respondWith(){assert.fail('must not handle');}});});
test('offline stylesheet uses cached asset',async()=>{const w=worker();w.stored.set('https://demo.test/assets/style.css',new Response('body{}'));let result;w.handlers.fetch({request:{url:'https://demo.test/assets/style.css',method:'GET',destination:'style',headers:new Headers()},respondWith(p){result=p;}});assert.equal(await (await result).text(),'body{}');assert.equal(w.calls,0);});
